# -*- coding: utf-8 -*-
"""ASSIGNMENT-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2YBGpLgOsPu0_lFXnQuDw4dBm1W9nM3
"""

import numpy as np
import pandas as pd



from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/data.csv")

df.head()

df.describe()

df.isnull().sum()

x = df['Calories'].mean()
print(x)

df['Calories'].fillna(x,inplace = True)

df.isnull().sum()

#4.Select at least two columns and aggregate the data using: min, max, count, mean.

selected_columns = ['Duration', 'Pulse']
aggregation = df[selected_columns].agg(['min','max','count','mean'])
print(aggregation)

#5.Filter the dataframe to select the rows with calories values between 500 and 1000.

filtered_df = df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]
print(filtered_df)

#6. Filter the dataframe to select the rows with calories values > 500 and pulse < 100

filter_df = df[(df['Calories'] > 500) & (df['Pulse'] < 100)]
print(filter_df)

#7. Create a new “df_modified” dataframe that contains all the columns from df except for “Maxpulse”.

df_modified = df.drop(columns=['Maxpulse'])
print(df_modified)

#8. Delete the “Maxpulse” column from the main df dataframe

df.drop(columns=['Maxpulse'], inplace=True)
print(df)

#9. Convert the datatype of Calories column to int datatype.
df['Calories'] = df['Calories'].astype(int)
df.dtypes

